apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  namespace: go-micro
spec:
  selector:
    app: go-web-app
  ports:
     - port: 80
       targetPort: 8080
       protocol: TCP
  type: LoadBalancer